### ISSUE TITLE
Error With RAT

### ISSUE THREAD

**Issue by karimawii** [AstraaDev/Discord-All-Tools-In-One#37]
I launch the python file that the RAT option creates with the bot token and the server ID, it creates a session channel and sends a notification message in it, but then it sends this in the console and doesn't setup slash commands :
```
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<SlashCommand.sync_all_commands() done, defined at C:\Users\bayan\AppData\Local\Programs\Python\Python310\lib\site-packages\discord_slash\client.py:416> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\bayan\AppData\Local\Programs\Python\Python310\lib\site-packages\discord_slash\client.py", line 440, in sync_all_commands
    existing_cmds = await self.req.get_all_commands(guild_id=scope)
  File "C:\Users\bayan\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
```

**Comment by YanisBleu** [comment]
Got the same problem
