### ISSUE TITLE
Error launching astraahome.py

### ISSUE THREAD

**Issue by arminask** [AstraaDev/Discord-All-Tools-In-One#9]
I use Pop!_OS 21.04

When I run: "python3 astraahome.py", I get this error:

Traceback (most recent call last):
  File "/home/arminas/Discord-All-Tools-In-One/astraahome.py", line 16, in <module>
    import discord
  File "/home/arminas/.local/lib/python3.9/site-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "/home/arminas/.local/lib/python3.9/site-packages/discord/client.py", line 38, in <module>
    from .state import ConnectionState
  File "/home/arminas/.local/lib/python3.9/site-packages/discord/state.py", line 36, in <module>
    from . import utils, compat
  File "/home/arminas/.local/lib/python3.9/site-packages/discord/compat.py", line 32
    create_task = asyncio.async
                          ^
SyntaxError: invalid syntax

Can someone help me?

**Comment by Misjudgments** [comment]
try to uninstall the discord module and reinstall it:
pip uninstall discord
pip install discord
try to replace python3 with just python
not an expert but I believe it should work.

**Comment by SpectrixDev** [comment]
[Answer to your problem](https://stackoverflow.com/questions/51196568/create-task-asyncio-async-syntaxerror-invalid-syntax)
